docs/index.html

######Explanation About What Code Achieves:
I naively copied the <script src="https://unpkg.com/frappe-charts@0.0.3/dist/frappe-charts.min.iife.js"/> from the docs and it silently broke parts of my page as chrome didn't parse some of my javascript. I've updated the docs page with the closing. Also matches https://www.npmjs.com/package/frappe-charts

replace self closing tag with closing tag in docs

---

README.md

I added a [jsDelivr CDN links](https://www.jsdelivr.com/package/npm/frappe-charts) to your readme as an alternative to unpkg. jsDelivr is the fastest opensource CDN available and built specifically for production usage. It can instantly serve any project from npm with zero config and offers a large network and better reliability.

Add alternative CDN

---

README.md

- Explanation
- Screenshot
- Steps
- None

Updated docs for es-modules like VueJS to work (import correction and including css)

---

package.json
yarn.lock

Bumping `node-sass` to `4.12.0`
Implements the fix from node-gyp, fixed here https://github.com/nodejs/node-gyp/pull/1455
RegExp bug in Node 10's xcode_emulation.py
```
version = re.match(r'(\\d\\.\\d\\.?\\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

fix: node-sass xcode rebuild issue

---

src/js/charts/PieChart.js
src/js/utils/draw.js

- Piechart could not render large arcs (>180) properly because the
information of large arc was not provided to the SVG drawing
function.
- This was fixed, and the piechart should render
correctly when one slice is larger than 180 degrees.
- Screenshot
- Without fix
- With fix
- Steps
- Build a piechart with one value larger than the sum of the remaining ones.
- For example: [4, 1, 1].
- Results in a potato-shaped piechart.
- With my code, you can see that it is rendered correctly.
- Verify that the fix does not break other visualizations.

Fix for issues #108 and #117

---

src/js/charts/AggregationChart.js
src/js/charts/PercentageChart.js

Before
After
Fix Legend Height

refactor: labels for aggregation/percentage chart

---

docs/index.html

Not sure why, but importing the Frappe charts simply from the module's own dir does not work (despite `module` being listed under `package.json`).
Since some issues have come up regarding this, I updated the docs to also mention the direct file import from the `dist/` folder.
Should the example point to the minified file path?

Update docs to show how ESM can be imported

---

src/js/charts/AxisChart.js
src/js/charts/BaseChart.js
src/js/utils/draw-utils.js
src/js/utils/draw.js

- Long legends would overlap with neighboring legends as shown in the screenshot below, added an option which when enabled, would truncate the legends.
1. Added `truncateString` in `draw-utils.js`
1. Added `truncateLegends` options to `config` object and passed it along to `legendBar` in `AxisChart.js`
1. Added a default value for max number of characters `LABEL_MAX_CHARS` in `draw.js`
> NOTE: The default value for `truncateLegends` is `0` (i.e. false)
`truncateLegends` not set (or set to false)
`truncateLegends` set as true

feat: added truncateLegends options

---

src/js/utils/constants.js

Fixes #201.
This is really a UX issue.
Previously, if any datapoint was a zero-value, it would still be visible on the chart, making it seem it has non-zero data.
Please pardon the insane precision on the values :smile: 
**Before:**
**After:**
- Refer to a bar or stacked bar chart with zero values - they shouldn't appear on the chart.
- I wasn't able to run the contribution steps locally, and I got the following error on `npm run dev`:
So I have no idea how to rebuild the distribution(s). That might need a separate commit/PR.

Remove minimum height for zero-values in bar chart

---

src/js/charts/DonutChart.js
src/js/charts/PieChart.js
src/js/utils/draw.js

Solves https://github.com/frappe/charts/issues/186
The PR adds a full circle check to pie chart and donut chart, this is required when a single data point is given to these charts, or when all but one data points have the value zero. 
Using the SVGs arc path, one can draw 99.999% of the circle but not a complete circle, this doesn't work because the starting point and ending point of the arc is the same for a circle, so I guess the browser does not bother to draw the SVG, it's similar to drawing a line from (10, 10) to (10, 10) you get no line. Normally it would be wise to use the `<circle>` tag, but that may require bigger changes and can be a part of a different release, so right now we use a clever hack to solve this problem. 
The `d` attribute will accept and draw all valid [`path …

feat: allow full circle in piechart

---

src/js/utils/intervals.js

This fixes an error that gets thrown whenever frappe is fed an empty array for its `datasets` property.
The error reads:
```
Uncaught TypeError: Reduce of empty array with no initial value
at Array.reduce (<anonymous>)
at getClosestInArray (frappe-charts.esm.js:2671)
```
- Initialise or call update on frappe-charts with `datasets: []`
- Not sure. Are there any tests that should be modified or created to cover this behaviour?

Fix reduce warning for empty arrays

---

docs/index.html
src/js/charts/BaseChart.js

Solving the following issues: https://github.com/frappe/charts/issues/168, https://github.com/frappe/charts/issues/210, https://github.com/frappe/charts/issues/200, https://github.com/frappe/charts/issues/168
- All these issues report that event listeners would not be removed properly causing issues in resizing, or when switching to a different view in SPAs
- The `boundDrawFn` was necessarily complicated, we need not attach it to a 'global' variable `BOUND_DRAW_FN`, it can be made available to `this`
- the `unbindWindowEvents` function (which unbinds all `window` events) is not a good naming choice for an API (It is renamed to `destroy`)
This PR fixes all of that.

fix: destroying event listener on window

---

src/js/charts/BaseChart.js

This PR allows disabling of animations.
Added an option `animate` with default value `1`.
Example usage:
```javascript
let typeChartArgs = {
title: "My Awesome Chart",
data: typeData,
type: 'axis-mixed',
height: 300,
animate: 0
};
```

feat: allow disabling animations using 'animate' option

---

src/js/charts/AxisChart.js

Sometimes when mouse-overing container, i got `vendors.app.js:8427 Uncaught TypeError: Cannot read property 'xPos' of undefined` that is caused by `-1` index
- To disable `-1` index tooltip when hovering container

Fix: Sometimes index === -1

---

src/js/utils/colors.js

use a different regex to check if passed string is a valid color by checking for both hex and rgb/hsl values. also, use a case-insensitive regex for checking hex colors.
fixes #274

fix: improve regex to check if string is hex or rgb

---

src/js/charts/Heatmap.js
src/js/objects/ChartComponents.js
src/js/utils/draw.js

Allow corner radius for heatmap
```javascript
let heatmapArgs = {
title: "Monthly Distribution",
data: heatmapData,
type: 'heatmap',
discreteDomains: 1,
countLabel: 'Level',
radius: 2,
colors: HEATMAP_COLORS_BLUE,
legendScale: [0, 1, 2, 4, 5]
};
let heatmapChart = new Chart("#chart-heatmap", heatmapArgs);
```

feat: allow corner radius for heatmap

---

src/js/charts/AxisChart.js

https://huntr.dev/users/arjunshibu has fixed the Cross-site Scripting (XSS) vulnerability 🔨. arjunshibu has been awarded $25 for fixing the vulnerability through the huntr bug bounty program 💵. Think you could fix a vulnerability like this?
Get involved at https://huntr.dev/
Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/charts/pull/1
GitHub Issue | https://github.com/frappe/charts/issues/313
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/npm/frappe-charts/1/README.md
`frappe-charts` is vulnerable to `Cross-Site Scripting (XSS)`.
`Cross-Site Scripting (XSS)` attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted websites. XSS attacks occur when an attacker uses a …

Security Fix for Cross-site Scripting (XSS) - huntr.dev

---

README.md
package.json
rollup.config.js

This is an attempt to fix https://github.com/frappe/charts/issues/199 (as well as [downstream issues](https://github.com/himynameisdave/svelte-frappe-charts/issues/32) in my `svelte-frappe-charts` wrapper library).
I tried to explain why this is happening [here](https://github.com/frappe/charts/issues/199#issuecomment-809623242). Allow me to summarize:
- Users who install this dependency and consume it the "modern way", via installing and importing it (as described in the README):
```typescript
import { Chart } from 'frappe-charts';
```
- By importing from `frappe-charts` (not a specific file like `.esm.js`), we are allowing our bundler to resolve what `frappe-charts` means.
- Generally bundlers mostly align with Node's [module resolution …

feat: use UMD instead of IIFE for browser target

---

.editorconfig
src/js/charts/AxisChart.js
src/js/objects/ChartComponents.js
src/js/utils/draw.js

You can now pass `numberFormatter` function in `axisOptions` to customize the behavior of number shortening. This is required in countries where K/M/B/T is not the standard way of shortening large numbers. E.g. India has thousands, lakh (1e5), crore (1e7).
The interface for this function is pretty simple
```javascript
(value) => {
// format value
return value
};
```
Outcome

feat: custom number formatter function

---

src/js/charts/BaseChart.js

It is just straightforward fixing. Currently, truncateLegends can never be false.

Fixed: Unrecognized falsy value of truncateLegends
